name: Calculate Wallet Deltas

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  calculate-deltas:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger = ${{ github.event_name }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install Packages
        run: |
          npm install
      
      - name: Run Program
        timeout-minutes: 50
        run: |
          node delta.js

      - name: Check Updates
        id: git-check
        run: echo "modified=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)" >> $GITHUB_OUTPUT

      - name: Commit Updates
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "updated $(date)"
          git pull --rebase --strategy-option=ours
          git push

      - run: echo "Status = ${{ job.status }}"
